import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // const res = await fetch('https://api.github.com/repos/vercel/next.js')
  // const data = await res.json()
  return (
    <html lang="en">
      {/* <head>{data.id}</head> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
